import { StyleSheet } from "react-native";
import { THEME } from "../constants/theme";

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: THEME.spacing.lg,
    paddingVertical: THEME.spacing.md,
    backgroundColor: THEME.colors.primary,
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  logoutBtn: {
    padding: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 8,
    color: THEME.colors.textSecondary,
    fontWeight: "600",
  },
  scrollContent: {
    paddingBottom: 32,
  },

  /* Hero Profile Banner */
  heroBanner: {
    backgroundColor: THEME.colors.primary,
    paddingBottom: 32,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  heroGradient: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 8,
  },
  largeAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "rgba(255,255,255,0.25)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.5)",
  },
  largeAvatarText: {
    color: "#FFFFFF",
    fontSize: 36,
    fontWeight: "900",
  },
  profileName: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  profileEmail: {
    fontSize: 12,
    color: "rgba(255,255,255,0.75)",
    marginTop: 4,
  },
  ageBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginTop: 8,
  },
  ageBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },

  /* Navigation Menu */
  menuCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginHorizontal: THEME.spacing.md,
    marginTop: -20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  /* Edit Form */
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginHorizontal: THEME.spacing.md,
    marginTop: THEME.spacing.md,
    padding: THEME.spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    gap: THEME.spacing.md,
  },
  formSectionTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: THEME.colors.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    borderRadius: 14,
  },
  inputIcon: {
    paddingHorizontal: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 12,
    fontSize: 13,
    color: THEME.colors.textPrimary,
  },
  saveButton: {
    backgroundColor: THEME.colors.primary,
    borderRadius: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  saveButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },

  /* Section Cards */
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    marginHorizontal: THEME.spacing.md,
    marginTop: THEME.spacing.md,
    padding: THEME.spacing.lg,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: THEME.colors.textPrimary,
  },
  sectionCount: {
    fontSize: 12,
    fontWeight: "800",
    color: THEME.colors.textSecondary,
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  emptyBlockText: {
    fontSize: 12,
    color: THEME.colors.textSecondary,
    fontStyle: "italic",
  },
  addressList: {
    gap: 10,
  },
  addressCardItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    gap: 10,
  },
  addressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: THEME.colors.primary,
    marginTop: 5,
  },
  addressStreet: {
    fontSize: 13,
    fontWeight: "800",
    color: THEME.colors.textPrimary,
  },
  addressSub: {
    fontSize: 11,
    color: THEME.colors.textSecondary,
    marginTop: 2,
  },

  /* Favourites */
  favScrollRow: {
    gap: 10,
    paddingRight: 4,
  },
  favItemCard: {
    width: 120,
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
  },
  favImage: {
    width: "100%",
    height: 90,
    backgroundColor: "#E2E8F0",
  },
  favName: {
    fontSize: 11,
    fontWeight: "800",
    color: THEME.colors.textPrimary,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  favPrice: {
    fontSize: 12,
    fontWeight: "900",
    color: THEME.colors.error,
    paddingHorizontal: 8,
    paddingBottom: 8,
    marginTop: 2,
  },

  /* Logout Card */
  logoutCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginHorizontal: THEME.spacing.md,
    marginTop: THEME.spacing.md,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#FCA5A5",
  },
  logoutCardText: {
    fontSize: 14,
    fontWeight: "800",
    color: THEME.colors.error,
  },
  infoDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  infoDetailTextCol: {
    flex: 1,
  },
  infoDetailLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoDetailValue: {
    fontSize: 13,
    fontWeight: "600",
    color: "#334155",
    marginTop: 2,
  },
});
